site_name: Manual da CAEPRO
site_author: CAEPRO UFPI
nav:
    - Início: index.md
    - SIGAA: sigaa.md
    - Agradecimentos: agradecimentos.md
    
theme:
  name: material
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Mudar para o tema escuro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Mudar para o tema claro
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/caeproufpi
      name: Instragram da CAEPRO UFPI
plugins:
    - search:
    - with-pdf:
        cover_subtitle: Escrito por estudantes para estudantes
        cover_logo: logo.jpg
        copyright: Documento livre
        toc_title: Sumário
