= MANUAL DA CAEPRO

== Manual da CAEPRO

=== Objetivo

O foco é apenas um: ajudar a comunidade de Engenharia de Produção da UFPI

=== Serviços

Temos uma página online elegante criada usando https://github.com/rust-lang/mdBook[mdBook]. A página pode ser acessada de qualquer navegador no seguinte endereço: https://maupdoc.github.io/Manual-da-CAEPRO/

Além disso, ofertamos versões em https://github.com/maupdoc/Manual-da-CAEPRO/raw/main/asciidoc_build/book.epub[EPUB] e em https://github.com/maupdoc/Manual-da-CAEPRO/raw/main/asciidoc_build/book.pdf[PDF] para quem achar mais prático.

== Colaboração

=== Estrutura do projeto

Os documentos que compõem o Manual estão listados e devem ser editados na pasta https://github.com/maupdoc/Manual-da-CAEPRO/tree/main/src[src]. Nessa pasta, há o SUMMARY.md que indica quais arquivos (escritos em Markdown) são incluídos no resultado final do Manual e como são organizados na hierarquia.

É *muito importante* seguir a convenção de nomes para os arquivos, pois facilita a compreensão e a execução de scripts essenciais para o projeto. A convenção adotada é juntar o número do capítulo, número do subcapítulo e o título do documento unidos com hífen . Exemplos:

* ch00-00-introducao.md (capítulo 0, subcapítulo 0, título legível: introducao)
* ch00-01-subintroducao.md (capítulo 0, subcapítulo 1, título legível: subintroducao)

A construção do SUMMARY.md está detalhado na https://rust-lang.github.io/mdBook/format/summary.html[documentação do mdBook].

== Introdução ao Manual da CAEPRO

Boas-vindas ao Manual da CAEPRO, digo, futuro Manual da CAEPRO, se você nos ajudar! O que seria isso, afinal? O Manual da CAEPRO é uma das propostas da chapa EVOlução com os seguintes pontos em mente:

* Documentar as principais dúvidas dos calouros e veteranos.
* Ter uma documentação de fácil acesso.
* Revelar os mistérios do SIGAA.
* Revelar alguns processos da UFPI: estágios, monitoria, iniciação científica e etc.
* Apoiar os alunos com recursos externos como links úteis.

Se você está lendo isso online, parabéns, acaba de conhecer a futura plataforma do Manual.

Pretendemos honrar nossos valores EVO: Estratégia, Visão e Objetivo. E para isso, listamos nossas outras propostas:

* Evoluir e manter os antigos projetos da última gestão da CAEPRO como o "Divulgaê" e a "Semana do Calouro". Afinal, queremos ser a evolução. Além disso, novos projetos surgem com a evolução, leia mais para saber quais.
* Criar um servidor no Discord para uma melhor comunicação e união da comunidade. Receber feedback e solução de dúvidas com texto, vídeo e áudio em tempo real é tudo possível no Discord.
* Trazer o mundo real da engenharia para os alunos com o projeto "Exercitando a Produção". Esse projeto desenvolverá trabalho em equipe, oficinas e palestras relevantes para o curso.
* Três palavras essenciais que não podem faltar: acessibilidade, transparência e comunicação. Pretendemos trazer isso sempre que possível, exemplo disso são as publicações com texto alternativo no Instagram.
* Depois dessa maratona de propostas, lembre-se que acreditamos no valor do esporte como meio de desenvolvimento físico e social. Por isso, tentaremos o possível para fomentar ainda mais o esporte seja físico ou eSports.

Parece incrível, né? Tudo isso só depende de você para se tornar realidade. Vote na chapa EVOlução e traga a evolução para a CAEPRO.
