name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      - run: pip install mdx-gh-links
      - run: pip install mkdocs-minify-plugin
      - run: pip install weasyprint
      - run: pip install mkdocs-with-pdf
      
      - run: mkdocs gh-deploy --force

